version: '3.1'

services:
  app:
    container_name: lsb-backend
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - 3300:3300
    depends_on:
      - db

  db:
    image: mysql
    container_name: lsb-db
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lsb
      MYSQL_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
