version: '3.1'

services:
  app:
    container_name: lsb-backend
    build:
      context: .
    env_file:
      - .env.prod
    expose:
      - 3300
    networks:
      - nginx_proxy_default
    volumes:
      - ./docker_data/static:/code/static
    depends_on:
      - db

  db:
    image: mysql
    container_name: lsb-db
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.prod
    volumes:
      - ./docker_data/data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nginx_proxy_default

networks:
  nginx_proxy_default:
    external: true
